[dependencies]
byteorder = "1.5.0"
clap = {version = "4.5.23", features = ["derive"]}
clap-stdin = "0.6.0"
# serde_json = "1.0.134"
# serde = { version = "1.0", features = ["derive"] }
pcsc = "2.9.0"

[package]
name = "oath-rs-experiments"
version = "0.1.0"
edition = "2021"
authors = ["Grimmauld <grimmauld@grimmauld.de>"]
description = "experiments with smartcards"
license-file = "LICENSE"
